In [1]:
import numpy as np
import pandas as pd

In [2]:
bins_arr = np.array([])
bins_arr = np.hstack((bins_arr, (np.ones(10) * 20000).cumsum()))

In [3]:
bins_arr

array([ 20000.,  40000.,  60000.,  80000., 100000., 120000., 140000.,
       160000., 180000., 200000.])

In [4]:
np.hstack((bins_arr, np.hstack((np.array([bins_arr[-1]]), (np.ones(10) * 20000))).cumsum()[1:]))

array([ 20000.,  40000.,  60000.,  80000., 100000., 120000., 140000.,
       160000., 180000., 200000., 220000., 240000., 260000., 280000.,
       300000., 320000., 340000., 360000., 380000., 400000.])

In [5]:
bins_arr+20

array([ 20020.,  40020.,  60020.,  80020., 100020., 120020., 140020.,
       160020., 180020., 200020.])

In [6]:
bins_arr = np.hstack((np.array([200]), bins_arr))

In [7]:
bins_arr

array([   200.,  20000.,  40000.,  60000.,  80000., 100000., 120000.,
       140000., 160000., 180000., 200000.])

In [8]:
test = [(1,2),(2,3)]
inde = [1,2]

In [19]:
mapper = dict(zip(inde,test))
mapper

{1: (1, 2), 2: (2, 3)}

In [10]:
pd.cut([20,50,300,500],bins=[15,50,100,700],labels=[1,2,3])

[1, 1, 3, 3]
Categories (3, int64): [1 < 2 < 3]

In [20]:
pd.Series([1,2]).map(mapper)

0    (1, 2)
1    (2, 3)
dtype: object

In [22]:
pd.Series([1,2]).map(mapper).apply(lambda x: x[1]) # upper range

0    2
1    3
dtype: int64

In [24]:
pd.Series([1,2]).map(mapper).apply(lambda x: x[0]) # lower range

0    1
1    2
dtype: int64

In [26]:
pd.DateOffset(months=6 - 1)

<DateOffset: months=5>